### ISSUE TITLE
doesnt work anymore

### ISSUE THREAD

**Issue by Duoquadragesimal** [einzigartigerName/spicetify-copy#2]
it just doesn't work, no errors in console log but it doesn't show up for me with spicetify v2 on spotify 1.1.62

**Comment by nelsongillo** [comment]
I know, it says in the [README](https://github.com/einzigartigerName/spicetify-copy#spicetify-copy-for-spotify-v1156-or-older) that only Spotify versions 1.1.56 and older are supported (using spicetify v1).
I was busy and had no time updating my extensions to spicetfy v2.
